jobs:
  build-chain:
    concurrency:
      cancel-in-progress: true
      group: jbpm-${{ matrix.java-version }}-pull_request-${{ github.head_ref }}
    name: ${{ matrix.os }} - Java ${{ matrix.java-version }} - Maven
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: ${{ matrix.os == 'windows-latest' }}
      name: Support long paths
      uses: kiegroup/kie-ci/.ci/actions/long-paths@main
    - continue-on-error: true
      name: Java and Maven Setup
      uses: kiegroup/kie-ci/.ci/actions/maven@main
      with:
        cache-key-prefix: ${{ runner.os }}-${{ matrix.java-version }}-maven${{ matrix.maven-version
          }}
        java-version: ${{ matrix.java-version }}
        maven-version: ${{ matrix.maven-version }}
    - continue-on-error: true
      name: Build Chain
      uses: kiegroup/kie-ci/.ci/actions/build-chain@main
      with:
        annotations-prefix: ${{ runner.os }}-${{ matrix.java-version }}/${{ matrix.maven-version
          }}
        definition-file: https://raw.githubusercontent.com/${GROUP:kiegroup}/droolsjbpm-build-bootstrap/${BRANCH:main}/.ci/pull-request-config.yaml
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      if: ${{ always() }}
      name: Surefire Report
      uses: kiegroup/kie-ci/.ci/actions/surefire-report@main
    strategy:
      fail-fast: true
      matrix:
        java-version:
        - 8
        - 11
        maven-version:
        - 3.8.1
        os:
        - ubuntu-latest
name: Build Chain
on:
  repository_dispatch:
    types: trigger-ga___pull_request.yml
